undefine SCHEMA_NAME
undefine OLD_TABLE_NAME
undefine NEW_TABLE_NAME
DECLARE
  num_errors PLS_INTEGER;
BEGIN
  DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS ('&&SCHEMA_NAME',  '&&OLD_TABLE_NAME', '&&NEW_TABLE_NAME',
    DBMS_REDEFINITION.CONS_ORIG_PARAMS, TRUE, TRUE, TRUE, TRUE, num_errors);
END;
/
